apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  # ClusterIP: 클러스터 내부에서만 접근 가능한 고정 IP를 할당합니다.
  # (Ingress가 이 IP로 트래픽을 전달합니다.)
  type: ClusterIP 
  selector:
    app: flask-app # deployment.yaml의 라벨과 일치
  ports:
  - protocol: TCP
    port: 80 # 서비스가 노출할 포트
    targetPort: 8000 # 파드(Gunicorn)가 실행 중인 포트