name: CI - Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때만 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. GitHub 레포지토리 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS 자격 증명 설정
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # Terraform으로 생성한 리전

    # 3. Amazon ECR 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Docker 이미지 빌드 및 ECR로 푸시
    - name: Build, tag, and push image to Amazon ECR
      env:
        # Terraform output에서 확인한 ECR 주소
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: project-cluster-flask-app # Terraform ecr.tf에서 정한 이름
        IMAGE_TAG: ${{ github.sha }} # Git 커밋 해시를 이미지 태그로 사용
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG